
name:  PR Build with Jekyll + TinaCMS before approving merge to main

on:
  # Runs on pushes targeting the default branch
  pull_request:
    branches: ["main"]
    paths-ignore:
      - 'Documentation/**'
      - 'Archive/**'
      - '.github/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  id-token: write


jobs:
  automerge:
      runs-on: ubuntu-latest
      if: github.actor == 'dependabot[bot]'
      steps:
        - uses: peter-evans/enable-pull-request-automerge@v3
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            pull-request-number: ${{ github.event.pull_request.number }}

  install-node:
    runs-on: ubuntu-latest
    steps:
      - name: install Node
        uses: actions/setup-node@v6
        with:
          node-version: "latest"

  # Build job
  pr-build:
    runs-on: ubuntu-latest
    needs: [install-node]    
    steps:      
      - name: Checkout PR
        uses: actions/checkout@v6
        with:
          ref: ${{github.ref}}
          clean: false

      - name: run NPM CI
        run: npm ci

      - name: Build TinaCMS (Index PR branch)
        env:
          TINA_PUBLIC_CLIENT_ID: ${{ secrets.TINA_PUBLIC_CLIENT_ID }}
          TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
          HEAD: ${{ github.head_ref}}
          TINA_SEARCH: ${{secrets.TINA_SEARCH}}
        run: npx tinacms build -v --skip-indexing --skip-cloud-checks --skip-search-index
        
      - name: Build Main with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site


