 #Sample workflow for building and deploying a Jekyll site to GitHub Pages
name:  PR Build with Jekyll + TinaCMS before approving merge to main

on:
  # Runs on pushes targeting the default branch
  pull_request:
    branches: ["main"]
    paths-ignore:
      - '.github/**'
      - 'Documentation/**'
      - 'Archive/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write




jobs:

  setup-pages:
    runs-on: ubuntu-latest 
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

  install-node:
    runs-on: ubuntu-latest
    steps:
      - name: install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

  # checkout:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Main
  #       uses: actions/checkout@v4
  #       with: 
  #         ref: main
  #         clean: false


  #     - uses: actions/checkout@v2
  #       name: Checkout Staging
  #       with:
  #         ref: staging
  #         # Put the checked out files inside the `big-island-buses/heleon` folder
  #         path: staging/
  #         clean: false
  #     # Delete the .git folder from `big-island-buses/heleon`
  #     # This turns the files into a plain folder instead of a git repository
  #     - run: rm -rf staging/.git
  



  # Build job
  build:
    runs-on: ubuntu-latest
    needs: [setup-pages, install-node]
    # env:
    #  TBA_AUT_KEY: ${{ secrets.TBA_API_KEY }}
    
    steps:      

      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{github.ref}}
          clean: false


      # - uses: actions/checkout@v2
      #   name: Checkout Staging
      #   with:
      #     ref: staging
      #     # Put the checked out files inside the `big-island-buses/heleon` folder
      #     path: staging/
      #     clean: false
      # # Delete the .git folder from `big-island-buses/heleon`
      # # This turns the files into a plain folder instead of a git repository
      # - run: rm -rf staging/.git

      # - name: run NPM install ./main/
      #   run: npm install

      - name: run NPM CI
        run: npm ci

      - name: Build TinaCMS (no indexing)
        env:
          BUILD_PATH: ${{vars.BUILD_PATH}}
          TINA_PUBLIC_CLIENT_ID: ${{ secrets.TINA_PUBLIC_CLIENT_ID }}
          TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
          #HEAD: ${{ github.ref_name}}
          TINA_SEARCH: ${{secrets.TINA_SEARCH}}
        run: npx tinacms build --skip-indexing --upstream-branch main
        
      - name: Build Main with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site


